### ISSUE TITLE
bug: not written in rust

### ISSUE THREAD

**Issue by dada513** [binex-dsk/pacebin#1]
These are source code written in C, an obsolete and dangerous programming language. The second command produces no output at all, which suggests that pacebin is, in fact, not written in Rust. Rust is a modern, safe programming language, featuring fearless abstractions and zero-cost concurrency. It's objectively superior to C and every other language in every way, therefore pacebin should be rewritten in Rust as soon as possible.

run `find -name '*.c'`, followed by `find -name '*.rs'`.

**Comment by binex-dsk** [comment]
1. Feature
2. Older commits contain memory leaks. Use those for maximum safety.
